#include "decode_instruction.h"

Instruction instructions[0x100] = {
    {BRK, IMPLIED, 1, 7},
    {ORA, INDEXED_INDIRECT, 2, 6},
    {0},
    {0},
    {0},
    {ORA, ZERO_PAGE, 2, 3},
    {ASL, ZERO_PAGE, 2, 5},
    {0},
    {PHP, IMPLIED, 1, 3},
    {ORA, IMMEDIATE, 2, 2},
    {ASL, ACCUMULATOR, 1, 2},
    {0},
    {0},
    {ORA, ABSOLUTE, 3, 4},
    {ASL, ABSOLUTE, 3, 6},
    {0},
    {BPL, RELATIVE, 2, 2},
    {ORA, INDIRECT_INDEXED, 2, 5},
    {0},
    {0},
    {0},
    {ORA, ZERO_PAGE_INDEXED_X, 2, 4},
    {ASL, ZERO_PAGE_INDEXED_X, 2, 6},
    {0},
    {CLC, IMPLIED, 1, 2},
    {ORA, ABSOLUTE_INDEXED_Y, 3, 4},
    {0},
    {0},
    {0},
    {ORA, ABSOLUTE_INDEXED_X, 3, 4},
    {ASL, ABSOLUTE_INDEXED_X, 3, 7},
    {0},
    {JSR, ABSOLUTE, 3, 6},
    {AND, INDEXED_INDIRECT, 2, 6},
    {0},
    {0},
    {BIT, ZERO_PAGE, 2, 3},
    {AND, ZERO_PAGE, 2, 3},
    {ROL, ZERO_PAGE, 2, 5},
    {0},
    {PLP, IMPLIED, 1, 4},
    {AND, IMMEDIATE, 2, 2},
    {ROL, ACCUMULATOR, 1, 2},
    {0},
    {BIT, ABSOLUTE, 3, 4},
    {AND, ABSOLUTE, 3, 4},
    {ROL, ABSOLUTE, 3, 6},
    {0},
    {BMI, RELATIVE, 2, 2},
    {AND, INDIRECT_INDEXED, 2, 5},
    {0},
    {0},
    {0},
    {AND, ZERO_PAGE_INDEXED_X, 2, 4},
    {ROL, ZERO_PAGE_INDEXED_X, 2, 6},
    {0},
    {SEC, IMPLIED, 1, 2},
    {AND, ABSOLUTE_INDEXED_Y, 3, 4},
    {0},
    {0},
    {0},
    {AND, ABSOLUTE_INDEXED_X, 3, 4},
    {ROL, ABSOLUTE_INDEXED_X, 3, 7},
    {0},
    {RTI, IMPLIED, 1, 6},
    {EOR, INDEXED_INDIRECT, 2, 6},
    {0},
    {0},
    {0},
    {EOR, ZERO_PAGE, 2, 3},
    {LSR, ZERO_PAGE, 2, 5},
    {0},
    {PHA, IMPLIED, 1, 3},
    {EOR, IMMEDIATE, 2, 2},
    {LSR, ACCUMULATOR, 1, 2},
    {0},
    {JMP, ABSOLUTE, 3, 3},
    {EOR, ABSOLUTE, 3, 4},
    {LSR, ABSOLUTE, 3, 6},
    {0},
    {BVC, RELATIVE, 2, 2},
    {EOR, INDIRECT_INDEXED, 2, 5},
    {0},
    {0},
    {0},
    {EOR, ZERO_PAGE_INDEXED_X, 2, 4},
    {LSR, ZERO_PAGE_INDEXED_X, 2, 6},
    {0},
    {CLI, IMPLIED, 1, 2},
    {EOR, ABSOLUTE_INDEXED_Y, 3, 4},
    {0},
    {0},
    {0},
    {EOR, ABSOLUTE_INDEXED_X, 3, 4},
    {LSR, ABSOLUTE_INDEXED_X, 3, 7},
    {0},
    {RTS, IMPLIED, 1, 6},
    {ADC, INDEXED_INDIRECT, 2, 6},
    {0},
    {0},
    {0},
    {ADC, ZERO_PAGE, 2, 3},
    {ROR, ZERO_PAGE, 2, 5},
    {0},
    {PLA, IMPLIED, 1, 4},
    {ADC, IMMEDIATE, 2, 2},
    {ROR, ACCUMULATOR, 1, 2},
    {0},
    {JMP, INDIRECT_ABSOLUTE, 3, 5},
    {ADC, ABSOLUTE, 3, 4},
    {ROR, ABSOLUTE_INDEXED_X, 3, 7},
    {0},
    {BVS, RELATIVE, 2, 2},
    {ADC, INDIRECT_INDEXED, 2, 5},
    {0},
    {0},
    {0},
    {ADC, ZERO_PAGE_INDEXED_X, 2, 4},
    {ROR, ZERO_PAGE_INDEXED_X, 2, 6},
    {0},
    {SEI, IMPLIED, 1, 2},
    {ADC, ABSOLUTE_INDEXED_Y, 3, 4},
    {0},
    {0},
    {0},
    {ADC, ABSOLUTE_INDEXED_X, 3, 4},
    {ROR, ABSOLUTE, 3, 6},
    {0},
    {0},
    {STA, INDEXED_INDIRECT, 2, 6},
    {0},
    {0},
    {STY, ZERO_PAGE, 2, 3},
    {STA, ZERO_PAGE, 2, 3},
    {STX, ZERO_PAGE, 2, 3},
    {0},
    {DEY, IMPLIED, 1, 2},
    {0},
    {TXA, IMPLIED, 1, 2},
    {0},
    {STY, ABSOLUTE, 3, 4},
    {STA, ABSOLUTE, 3, 4},
    {STX, ABSOLUTE, 3, 4},
    {0},
    {BCC, RELATIVE, 2, 2},
    {STA, INDIRECT_INDEXED, 2, 6},
    {0},
    {0},
    {STY, ZERO_PAGE_INDEXED_X, 2, 4},
    {STA, ZERO_PAGE_INDEXED_X, 2, 4},
    {STX, ZERO_PAGE_INDEXED_Y, 2, 4},
    {0},
    {TYA, IMPLIED, 1, 2},
    {STA, ABSOLUTE_INDEXED_Y, 3, 5},
    {TXS, IMPLIED, 1, 2},
    {0},
    {0},
    {STA, ABSOLUTE_INDEXED_X, 3, 5},
    {0},
    {0},
    {LDY, IMMEDIATE, 2, 2},
    {LDA, INDEXED_INDIRECT, 2, 6},
    {LDX, IMMEDIATE, 2, 2},
    {0},
    {LDY, ZERO_PAGE, 2, 3},
    {LDA, ZERO_PAGE, 2, 3},
    {LDX, ZERO_PAGE, 2, 3},
    {0},
    {TAY, IMPLIED, 1, 2},
    {LDA, IMMEDIATE, 2, 2},
    {TAX, IMPLIED, 1, 2},
    {0},
    {LDY, ABSOLUTE, 3, 4},
    {LDA, ABSOLUTE, 3, 4},
    {LDX, ABSOLUTE, 3, 4},
    {0},
    {BCS, RELATIVE, 2, 2},
    {LDA, INDIRECT_INDEXED, 2, 5},
    {0},
    {0},
    {LDY, ZERO_PAGE_INDEXED_X, 2, 4},
    {LDA, ZERO_PAGE_INDEXED_X, 2, 4},
    {LDX, ZERO_PAGE_INDEXED_Y, 2, 4},
    {0},
    {CLV, IMPLIED, 1, 2},
    {LDA, ABSOLUTE_INDEXED_Y, 3, 4},
    {TSX, IMPLIED, 1, 2},
    {0},
    {LDY, ABSOLUTE_INDEXED_X, 3, 4},
    {LDA, ABSOLUTE_INDEXED_X, 3, 4},
    {LDX, ABSOLUTE_INDEXED_Y, 3, 4},
    {0},
    {CPY, IMMEDIATE, 2, 2},
    {CMP, INDEXED_INDIRECT, 2, 6},
    {0},
    {0},
    {CPY, ZERO_PAGE, 2, 3},
    {CMP, ZERO_PAGE, 2, 3},
    {DEC, ZERO_PAGE, 2, 5},
    {0},
    {INY, IMPLIED, 1, 2},
    {CMP, IMMEDIATE, 2, 2},
    {DEX, IMPLIED, 1, 2},
    {0},
    {CPY, ABSOLUTE, 3, 4},
    {CMP, ABSOLUTE, 3, 4},
    {DEC, ABSOLUTE, 3, 6},
    {0},
    {BNE, RELATIVE, 2, 2},
    {CMP, INDIRECT_INDEXED, 2, 5},
    {0},
    {0},
    {0},
    {CMP, ZERO_PAGE_INDEXED_X, 2, 4},
    {DEC, ZERO_PAGE_INDEXED_X, 2, 6},
    {0},
    {CLD, IMPLIED, 1, 2},
    {CMP, ABSOLUTE_INDEXED_Y, 3, 4},
    {0},
    {0},
    {0},
    {CMP, ABSOLUTE_INDEXED_X, 3, 4},
    {DEC, ABSOLUTE_INDEXED_X, 3, 7},
    {0},
    {CPX, IMMEDIATE, 2, 2},
    {SBC, INDEXED_INDIRECT, 2, 6},
    {0},
    {0},
    {CPX, ZERO_PAGE, 2, 3},
    {SBC, ZERO_PAGE, 2, 3},
    {INC, ZERO_PAGE, 2, 5},
    {0},
    {INX, IMPLIED, 1, 2},
    {SBC, IMMEDIATE, 2, 2},
    {NOP, IMPLIED, 1, 2},
    {0},
    {CPX, ABSOLUTE, 3, 4},
    {SBC, ABSOLUTE, 3, 4},
    {INC, ABSOLUTE, 3, 6},
    {0},
    {BEQ, RELATIVE, 2, 2},
    {SBC, INDIRECT_INDEXED, 2, 5},
    {0},
    {0},
    {0},
    {SBC, ZERO_PAGE_INDEXED_X, 2, 4},
    {INC, ZERO_PAGE_INDEXED_X, 2, 6},
    {0},
    {SED, IMPLIED, 1, 2},
    {SBC, ABSOLUTE_INDEXED_Y, 3, 4},
    {0},
    {0},
    {0},
    {SBC, ABSOLUTE_INDEXED_X, 3, 4},
    {INC, ABSOLUTE_INDEXED_X, 3, 7},
    {0},
};

Instruction decode_instruction(uint8_t opcode) { return instructions[opcode]; }
