#include "decode_instruction.h"

Instruction instructions[0x100] = {
    {BRK, "BRK", IMPLIED, 1, 7},
    {ORA, "ORA", INDEXED_INDIRECT, 2, 6},
    {0},
    {0},
    {0},
    {ORA, "ORA", ZERO_PAGE, 2, 3},
    {ASL, "ASL", ZERO_PAGE, 2, 5},
    {0},
    {PHP, "PHP", IMPLIED, 1, 3},
    {ORA, "ORA", IMMEDIATE, 2, 2},
    {ASL, "ASL", ACCUMULATOR, 1, 2},
    {0},
    {0},
    {ORA, "ORA", ABSOLUTE, 3, 4},
    {ASL, "ASL", ABSOLUTE, 3, 6},
    {0},
    {BPL, "BPL", RELATIVE, 2, 2},
    {ORA, "ORA", INDIRECT_INDEXED, 2, 5},
    {0},
    {0},
    {0},
    {ORA, "ORA", ZERO_PAGE_INDEXED_X, 2, 4},
    {ASL, "ASL", ZERO_PAGE_INDEXED_X, 2, 6},
    {0},
    {CLC, "CLC", IMPLIED, 1, 2},
    {ORA, "ORA", ABSOLUTE_INDEXED_Y, 3, 4},
    {0},
    {0},
    {0},
    {ORA, "ORA", ABSOLUTE_INDEXED_X, 3, 4},
    {ASL, "ASL", ABSOLUTE_INDEXED_X, 3, 7},
    {0},
    {JSR, "JSR", ABSOLUTE, 3, 6},
    {AND, "AND", INDEXED_INDIRECT, 2, 6},
    {0},
    {0},
    {BIT, "BIT", ZERO_PAGE, 2, 3},
    {AND, "AND", ZERO_PAGE, 2, 3},
    {ROL, "ROL", ZERO_PAGE, 2, 5},
    {0},
    {PLP, "PLP", IMPLIED, 1, 4},
    {AND, "AND", IMMEDIATE, 2, 2},
    {ROL, "ROL", ACCUMULATOR, 1, 2},
    {0},
    {BIT, "BIT", ABSOLUTE, 3, 4},
    {AND, "AND", ABSOLUTE, 3, 4},
    {ROL, "ROL", ABSOLUTE, 3, 6},
    {0},
    {BMI, "BMI", RELATIVE, 2, 2},
    {AND, "AND", INDIRECT_INDEXED, 2, 5},
    {0},
    {0},
    {0},
    {AND, "AND", ZERO_PAGE_INDEXED_X, 2, 4},
    {ROL, "ROL", ZERO_PAGE_INDEXED_X, 2, 6},
    {0},
    {SEC, "SEC", IMPLIED, 1, 2},
    {AND, "AND", ABSOLUTE_INDEXED_Y, 3, 4},
    {0},
    {0},
    {0},
    {AND, "AND", ABSOLUTE_INDEXED_X, 3, 4},
    {ROL, "ROL", ABSOLUTE_INDEXED_X, 3, 7},
    {0},
    {RTI, "RTI", IMPLIED, 1, 6},
    {EOR, "EOR", INDEXED_INDIRECT, 2, 6},
    {0},
    {0},
    {0},
    {EOR, "EOR", ZERO_PAGE, 2, 3},
    {LSR, "LSR", ZERO_PAGE, 2, 5},
    {0},
    {PHA, "PHA", IMPLIED, 1, 3},
    {EOR, "EOR", IMMEDIATE, 2, 2},
    {LSR, "LSR", ACCUMULATOR, 1, 2},
    {0},
    {JMP, "JMP", ABSOLUTE, 3, 3},
    {EOR, "EOR", ABSOLUTE, 3, 4},
    {LSR, "LSR", ABSOLUTE, 3, 6},
    {0},
    {BVC, "BVC", RELATIVE, 2, 2},
    {EOR, "EOR", INDIRECT_INDEXED, 2, 5},
    {0},
    {0},
    {0},
    {EOR, "EOR", ZERO_PAGE_INDEXED_X, 2, 4},
    {LSR, "LSR", ZERO_PAGE_INDEXED_X, 2, 6},
    {0},
    {CLI, "CLI", IMPLIED, 1, 2},
    {EOR, "EOR", ABSOLUTE_INDEXED_Y, 3, 4},
    {0},
    {0},
    {0},
    {EOR, "EOR", ABSOLUTE_INDEXED_X, 3, 4},
    {LSR, "LSR", ABSOLUTE_INDEXED_X, 3, 7},
    {0},
    {RTS, "RTS", IMPLIED, 1, 6},
    {ADC, "ADC", INDEXED_INDIRECT, 2, 6},
    {0},
    {0},
    {0},
    {ADC, "ADC", ZERO_PAGE, 2, 3},
    {ROR, "ROR", ZERO_PAGE, 2, 5},
    {0},
    {PLA, "PLA", IMPLIED, 1, 4},
    {ADC, "ADC", IMMEDIATE, 2, 2},
    {ROR, "ROR", ACCUMULATOR, 1, 2},
    {0},
    {JMP, "JMP", INDIRECT_ABSOLUTE, 3, 5},
    {ADC, "ADC", ABSOLUTE, 3, 4},
    {ROR, "ROR", ABSOLUTE_INDEXED_X, 3, 7},
    {0},
    {BVS, "BVS", RELATIVE, 2, 2},
    {ADC, "ADC", INDIRECT_INDEXED, 2, 5},
    {0},
    {0},
    {0},
    {ADC, "ADC", ZERO_PAGE_INDEXED_X, 2, 4},
    {ROR, "ROR", ZERO_PAGE_INDEXED_X, 2, 6},
    {0},
    {SEI, "SEI", IMPLIED, 1, 2},
    {ADC, "ADC", ABSOLUTE_INDEXED_Y, 3, 4},
    {0},
    {0},
    {0},
    {ADC, "ADC", ABSOLUTE_INDEXED_X, 3, 4},
    {ROR, "ROR", ABSOLUTE, 3, 6},
    {0},
    {0},
    {STA, "STA", INDEXED_INDIRECT, 2, 6},
    {0},
    {0},
    {STY, "STY", ZERO_PAGE, 2, 3},
    {STA, "STA", ZERO_PAGE, 2, 3},
    {STX, "STX", ZERO_PAGE, 2, 3},
    {0},
    {DEY, "DEY", IMPLIED, 1, 2},
    {0},
    {TXA, "TXA", IMPLIED, 1, 2},
    {0},
    {STY, "STY", ABSOLUTE, 3, 4},
    {STA, "STA", ABSOLUTE, 3, 4},
    {STX, "STX", ABSOLUTE, 3, 4},
    {0},
    {BCC, "BCC", RELATIVE, 2, 2},
    {STA, "STA", INDIRECT_INDEXED, 2, 6},
    {0},
    {0},
    {STY, "STY", ZERO_PAGE_INDEXED_X, 2, 4},
    {STA, "STA", ZERO_PAGE_INDEXED_X, 2, 4},
    {STX, "STX", ZERO_PAGE_INDEXED_Y, 2, 4},
    {0},
    {TYA, "TYA", IMPLIED, 1, 2},
    {STA, "STA", ABSOLUTE_INDEXED_Y, 3, 5},
    {TXS, "TXS", IMPLIED, 1, 2},
    {0},
    {0},
    {STA, "STA", ABSOLUTE_INDEXED_X, 3, 5},
    {0},
    {0},
    {LDY, "LDY", IMMEDIATE, 2, 2},
    {LDA, "LDA", INDEXED_INDIRECT, 2, 6},
    {LDX, "LDX", IMMEDIATE, 2, 2},
    {0},
    {LDY, "LDY", ZERO_PAGE, 2, 3},
    {LDA, "LDA", ZERO_PAGE, 2, 3},
    {LDX, "LDX", ZERO_PAGE, 2, 3},
    {0},
    {TAY, "TAY", IMPLIED, 1, 2},
    {LDA, "LDA", IMMEDIATE, 2, 2},
    {TAX, "TAX", IMPLIED, 1, 2},
    {0},
    {LDY, "LDY", ABSOLUTE, 3, 4},
    {LDA, "LDA", ABSOLUTE, 3, 4},
    {LDX, "LDX", ABSOLUTE, 3, 4},
    {0},
    {BCS, "BCS", RELATIVE, 2, 2},
    {LDA, "LDA", INDIRECT_INDEXED, 2, 5},
    {0},
    {0},
    {LDY, "LDY", ZERO_PAGE_INDEXED_X, 2, 4},
    {LDA, "LDA", ZERO_PAGE_INDEXED_X, 2, 4},
    {LDX, "LDX", ZERO_PAGE_INDEXED_Y, 2, 4},
    {0},
    {CLV, "CLV", IMPLIED, 1, 2},
    {LDA, "LDA", ABSOLUTE_INDEXED_Y, 3, 4},
    {TSX, "TSX", IMPLIED, 1, 2},
    {0},
    {LDY, "LDY", ABSOLUTE_INDEXED_X, 3, 4},
    {LDA, "LDA", ABSOLUTE_INDEXED_X, 3, 4},
    {LDX, "LDX", ABSOLUTE_INDEXED_Y, 3, 4},
    {0},
    {CPY, "CPY", IMMEDIATE, 2, 2},
    {CMP, "CMP", INDEXED_INDIRECT, 2, 6},
    {0},
    {0},
    {CPY, "CPY", ZERO_PAGE, 2, 3},
    {CMP, "CMP", ZERO_PAGE, 2, 3},
    {DEC, "DEC", ZERO_PAGE, 2, 5},
    {0},
    {INY, "INY", IMPLIED, 1, 2},
    {CMP, "CMP", IMMEDIATE, 2, 2},
    {DEX, "DEX", IMPLIED, 1, 2},
    {0},
    {CPY, "CPY", ABSOLUTE, 3, 4},
    {CMP, "CMP", ABSOLUTE, 3, 4},
    {DEC, "DEC", ABSOLUTE, 3, 6},
    {0},
    {BNE, "BNE", RELATIVE, 2, 2},
    {CMP, "CMP", INDIRECT_INDEXED, 2, 5},
    {0},
    {0},
    {0},
    {CMP, "CMP", ZERO_PAGE_INDEXED_X, 2, 4},
    {DEC, "DEC", ZERO_PAGE_INDEXED_X, 2, 6},
    {0},
    {CLD, "CLD", IMPLIED, 1, 2},
    {CMP, "CMP", ABSOLUTE_INDEXED_Y, 3, 4},
    {0},
    {0},
    {0},
    {CMP, "CMP", ABSOLUTE_INDEXED_X, 3, 4},
    {DEC, "DEC", ABSOLUTE_INDEXED_X, 3, 7},
    {0},
    {CPX, "CPX", IMMEDIATE, 2, 2},
    {SBC, "SBC", INDEXED_INDIRECT, 2, 6},
    {0},
    {0},
    {CPX, "CPX", ZERO_PAGE, 2, 3},
    {SBC, "SBC", ZERO_PAGE, 2, 3},
    {INC, "INC", ZERO_PAGE, 2, 5},
    {0},
    {INX, "INX", IMPLIED, 1, 2},
    {SBC, "SBC", IMMEDIATE, 2, 2},
    {NOP, "NOP", IMPLIED, 1, 2},
    {0},
    {CPX, "CPX", ABSOLUTE, 3, 4},
    {SBC, "SBC", ABSOLUTE, 3, 4},
    {INC, "INC", ABSOLUTE, 3, 6},
    {0},
    {BEQ, "BEQ", RELATIVE, 2, 2},
    {SBC, "SBC", INDIRECT_INDEXED, 2, 5},
    {0},
    {0},
    {0},
    {SBC, "SBC", ZERO_PAGE_INDEXED_X, 2, 4},
    {INC, "INC", ZERO_PAGE_INDEXED_X, 2, 6},
    {0},
    {SED, "SED", IMPLIED, 1, 2},
    {SBC, "SBC", ABSOLUTE_INDEXED_Y, 3, 4},
    {0},
    {0},
    {0},
    {SBC, "SBC", ABSOLUTE_INDEXED_X, 3, 4},
    {INC, "INC", ABSOLUTE_INDEXED_X, 3, 7},
    {0},
};

Instruction decode_instruction(uint8_t opcode) {
    return instructions[opcode];
}
